// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// count_spikes
IntegerMatrix count_spikes(IntegerVector group_index, int num_groups, NumericVector spike_time, NumericVector timesteps);
RcppExport SEXP _transmit_count_spikes(SEXP group_indexSEXP, SEXP num_groupsSEXP, SEXP spike_timeSEXP, SEXP timestepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type group_index(group_indexSEXP);
    Rcpp::traits::input_parameter< int >::type num_groups(num_groupsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type spike_time(spike_timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type timesteps(timestepsSEXP);
    rcpp_result_gen = Rcpp::wrap(count_spikes(group_index, num_groups, spike_time, timesteps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_transmit_count_spikes", (DL_FUNC) &_transmit_count_spikes, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_transmit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
